import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>InCryptoEncrypted</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <p className="text-3xl font-medium text-center">Welcome to the EncryptedClan 👋</p>
      </main>
    </>
  );
};

export default Home;
